# Generated by Django 2.1 on 2019-06-14 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contents', models.CharField(max_length=64, verbose_name='框架内容')),
                ('info', models.TextField(blank=True, max_length=200, null=True, verbose_name='说明')),
                ('parentId', models.IntegerField(default=0, verbose_name='父ID')),
            ],
            options={
                'verbose_name': 'case内容',
                'verbose_name_plural': 'case内容',
            },
        ),
        migrations.CreateModel(
            name='CaseIdeaContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=64, unique=True, verbose_name='框架内容')),
                ('info', models.TextField(blank=True, max_length=200, null=True, verbose_name='说明')),
                ('parentI_id', models.IntegerField(default=0, verbose_name='父ID')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='主题创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='主题更新时间')),
                ('caseContent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casepoint.CaseContent', verbose_name='case内容')),
            ],
            options={
                'verbose_name': '方案内容',
                'verbose_name_plural': '方案内容',
            },
        ),
        migrations.CreateModel(
            name='CaseIdeaTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='主题名称')),
                ('info', models.TextField(blank=True, max_length=200, null=True, verbose_name='说明')),
                ('viewPermissions', models.IntegerField(default=1, verbose_name='查看权限')),
                ('isValid', models.IntegerField(default=1, verbose_name='删除字段')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='主题创建时间')),
            ],
            options={
                'verbose_name': '方案主题',
                'verbose_name_plural': '方案主题',
            },
        ),
        migrations.CreateModel(
            name='CaseTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='主题名称')),
                ('info', models.TextField(blank=True, max_length=200, null=True, verbose_name='说明')),
                ('viewPermissions', models.IntegerField(default=1, verbose_name='查看权限')),
                ('is_valid', models.IntegerField(default=1, verbose_name='删除字段')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='主题创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='主题更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='框架分类')),
                ('info', models.CharField(blank=True, max_length=100, null=True, verbose_name='说明')),
                ('isValid', models.IntegerField(default=1, verbose_name='删除字段')),
            ],
        ),
        migrations.AddField(
            model_name='casetitle',
            name='caseType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casepoint.CaseType', verbose_name='主题分类'),
        ),
        migrations.AddField(
            model_name='casetitle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='caseideatitle',
            name='caseTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casepoint.CaseTitle', verbose_name='case标题'),
        ),
        migrations.AddField(
            model_name='caseideatitle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='caseideacontent',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casepoint.CaseIdeaTitle', verbose_name='框架id'),
        ),
        migrations.AddField(
            model_name='casecontent',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casepoint.CaseTitle', verbose_name='框架id'),
        ),
    ]
